import { build } from "esbuild";
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
const root = fileURLToPath(new URL("../", import.meta.url));
const dir = root + "examples/jev-choice-demo/vendor/";
const result = await build({
  stdin: { contents: 'export { z } from "zod";', resolveDir: root },
  bundle: true,
  format: "esm",
  platform: "node",
  target: "node26",
  minify: true,
  // Escape generated-code templates so the artifact has no literal trailing whitespace.
  supported: { "template-literal": false },
  legalComments: "none",
  write: false,
});
const content =
  "// Zod 4.4.3 (MIT). Generated by scripts/build-vendor.mjs; see ZOD-LICENSE.\n" +
  result.outputFiles[0].text;
const license = await readFile(
  new URL("../node_modules/zod/LICENSE", import.meta.url),
  "utf8",
);
for (const [name, data] of [
  ["zod.js", content],
  ["ZOD-LICENSE", license],
]) {
  if (process.argv.includes("--check")) {
    if ((await readFile(dir + name, "utf8")) !== data)
      throw new Error(name + " is stale; run pnpm build:vendor");
  } else await writeFile(dir + name, data);
}
